import './globals.css';

import { Box } from '@mui/material';
import type { Metadata } from 'next';

import { AppHeader } from '@/shared/components';
import { AppProviders } from '@/shared/providers';

export const metadata: Metadata = {
	title: {
		template: 'Snap flicks | %s',
		default: 'Snap flicks',
	},
	description: 'Generated by create next app',
};

interface Props {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Props): React.ReactElement {
	return (
		<html lang='en'>
			<body>
				<AppHeader />
				<AppProviders>
					<Box
						maxWidth='1500px'
						margin='auto'
						paddingInline={{ xs: '1rem', xl: '0rem' }}
					>
						{children}
					</Box>
				</AppProviders>
			</body>
		</html>
	);
}
