import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { GifSearch } from '@/gifs/components';
import ThemeRegistry from '@/ui/ThemeRegistry/ThemeRegistry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): React.ReactElement {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeRegistry>
					<h1>Gif Search</h1>
					<GifSearch />
					{children}
				</ThemeRegistry>
			</body>
		</html>
	);
}
