import './globals.css';

import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { HomeLink } from '@/shared/components';
import { AppProviders } from '@/shared/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface Props {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Props): React.ReactElement {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<AppProviders>
					<Box
						component='header'
						textAlign='center'
						display='flex'
						flexDirection='column'
					>
						<HomeLink>Snap flicks</HomeLink>
					</Box>

					{children}
				</AppProviders>
			</body>
		</html>
	);
}
